/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ConnectionRegistry {
      
    export type ConnectionStruct = {userA: AddressLike, userB: AddressLike, matchId: string, timestamp: BigNumberish}

    export type ConnectionStructOutput = [userA: string, userB: string, matchId: string, timestamp: bigint] & {userA: string, userB: string, matchId: string, timestamp: bigint }
  
    }

  export interface ConnectionRegistryInterface extends Interface {
    getFunction(nameOrSignature: "connectionCount" | "connections" | "getConnection" | "getConnectionByMatchId" | "matchExists" | "matchIdToIndex" | "owner" | "recordConnection" | "totalConnections" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConnectionRecorded" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'connectionCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'connections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getConnection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getConnectionByMatchId', values: [string]): string;
encodeFunctionData(functionFragment: 'matchExists', values: [string]): string;
encodeFunctionData(functionFragment: 'matchIdToIndex', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordConnection', values: [AddressLike, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'totalConnections', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'connectionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'connections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConnection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConnectionByMatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchIdToIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordConnection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalConnections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ConnectionRecordedEvent {
      export type InputTuple = [id: BigNumberish, userA: AddressLike, userB: AddressLike, matchId: string, timestamp: BigNumberish];
      export type OutputTuple = [id: bigint, userA: string, userB: string, matchId: string, timestamp: bigint];
      export interface OutputObject {id: bigint, userA: string, userB: string, matchId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ConnectionRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ConnectionRegistry;
    waitForDeployment(): Promise<this>;

    interface: ConnectionRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    connectionCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    connections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint] & {userA: string, userB: string, matchId: string, timestamp: bigint }],
      'view'
    >
    

    
    getConnection: TypedContractMethod<
      [id: BigNumberish, ],
      [ConnectionRegistry.ConnectionStructOutput],
      'view'
    >
    

    
    getConnectionByMatchId: TypedContractMethod<
      [matchId: string, ],
      [ConnectionRegistry.ConnectionStructOutput],
      'view'
    >
    

    
    matchExists: TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >
    

    
    matchIdToIndex: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordConnection: TypedContractMethod<
      [userA: AddressLike, userB: AddressLike, matchId: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    totalConnections: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'connectionCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'connections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint] & {userA: string, userB: string, matchId: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getConnection'): TypedContractMethod<
      [id: BigNumberish, ],
      [ConnectionRegistry.ConnectionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getConnectionByMatchId'): TypedContractMethod<
      [matchId: string, ],
      [ConnectionRegistry.ConnectionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'matchExists'): TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'matchIdToIndex'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordConnection'): TypedContractMethod<
      [userA: AddressLike, userB: AddressLike, matchId: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalConnections'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ConnectionRecorded'): TypedContractEvent<ConnectionRecordedEvent.InputTuple, ConnectionRecordedEvent.OutputTuple, ConnectionRecordedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ConnectionRecorded(uint256,address,address,string,uint256)': TypedContractEvent<ConnectionRecordedEvent.InputTuple, ConnectionRecordedEvent.OutputTuple, ConnectionRecordedEvent.OutputObject>;
      ConnectionRecorded: TypedContractEvent<ConnectionRecordedEvent.InputTuple, ConnectionRecordedEvent.OutputTuple, ConnectionRecordedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }